function DavisDaily = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  DAVISDAILY = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  DAVISDAILY = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  DAVISDAILY = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  DavisDaily = importfile("C:\Users\garellan\OneDrive - MathWorks\Documents - LATAM Team\2025\000_Events & Visits 2025\03_24_UNA\Codigo y datos\DavisDaily.xlsx", "DavisDaily", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 21-Mar-2025 08:36:39

%% Input handling

% If no sheet is specified, read from DavisDaily
if nargin == 1 || isempty(sheetName)
    sheetName = "DavisDaily";
end

% If row start and end points are not specified, define defaults
lastRowOfDataIdx = 0;
if nargin <= 2
    dataLines = [2, Inf];
    lastRowOfDataIdx = 1;
elseif dataLines(end,2) >= Inf
    lastRowOfDataIdx = size(dataLines, 1);
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 15);

% Specify sheet and range
opts.Sheet = sheetName;
if lastRowOfDataIdx == 1
    opts.DataRange = "A" + dataLines(1, 1);
else
    opts.DataRange = "A" + dataLines(1, 1) + ":O" + dataLines(1, 2);
end

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Date", "DayofYear", "Var6", "Var7", "SolRatio", "Var9", "MaxAirTemp", "MinAirTemp", "Var12", "Var13", "Var14", "AvgRelHum"];
opts.SelectedVariableNames = ["Date", "DayofYear", "SolRatio", "MaxAirTemp", "MinAirTemp", "AvgRelHum"];
opts.VariableTypes = ["char", "char", "char", "datetime", "double", "char", "char", "double", "char", "double", "double", "char", "char", "char", "double"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var6", "Var7", "Var9", "Var12", "Var13", "Var14"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var6", "Var7", "Var9", "Var12", "Var13", "Var14"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["DayofYear", "SolRatio", "MaxAirTemp", "MinAirTemp", "AvgRelHum"], "TreatAsMissing", '');

% Import the data
DavisDaily = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    if idx == lastRowOfDataIdx
        opts.DataRange = "A" + dataLines(idx, 1);
    else
        opts.DataRange = "A" + dataLines(idx, 1) + ":O" + dataLines(idx, 2);
    end
    tb = readtable(workbookFile, opts, "UseExcel", false);
    DavisDaily = [DavisDaily; tb]; %#ok<AGROW>
end

end